### ISSUE TITLE
SQL error: SQLSTATE[HY000] [2054] | The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by Reboot70** [EnergyCube/CoWFC#1]
I'm getting above error when I try to connect to the admin panel (server:80/?page=admin&section=Dashboard) of the server I set up with the Ubuntu installer script. I don't seem to have any issue connecting to my server locally from my Wii instances.

The device I installed this on is a Raspberry Pi 3B with Ubuntu Server 20.04.2 LTS.

Please let me know if I need to provide more information or if you'd like me to help debug

**Comment by EnergyCube** [comment]
The problem seems to be php related, can you check that it has been successfully installed?

**Comment by EnergyCube** [comment]
Any news ?

**Comment by EnergyCube** [comment]
No news since 2 month.
Reopen the issue if you have any news.

**Comment by quimodotcom** [comment]
Hello mr EnergyCube, am receiving this error too: There was an error: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client. can give you the following log and see if you can spot anything wrong! 
Creating Nintendo virtual hosts....
Done!
enabling....
Enabling site gamestats.gs.nintendowifi.net.
Enabling site gamestats2.gs.nintendowifi.net.
Enabling site nas-naswii-dls1-conntest.nintendowifi.net.
Enabling site sake.gs.nintendowifi.net.
To activate the new configuration, you need to run:
  systemctl reload apache2
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
Creating Wiimmfi virtual hosts....
Done!
enabling....
Enabling site gamestats.gs.wiimmfi.de.
Enabling site gamestats2.gs.wiimmfi.de.
Enabling site nas-naswii-dls1-conntest.wiimmfi.de.
Enabling site sake.gs.wiimmfi.de.
To activate the new configuration, you need to run:
  systemctl reload apache2
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
Enabling module proxy.
Considering dependency proxy for proxy_http:
Module proxy already enabled
Enabling module proxy_http.
To activate the new configuration, you need to run:
  systemctl restart apache2
Considering dependency mpm_prefork for php7.1:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.1:
Module php7.1 already enabled
mkdir: cannot create directory ‘/var/www/html’: File exists
Creating gpcm.db file
We will now configure MYSQL server.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcgi-fast-perl libcgi-pm-perl libencode-locale-perl libevent-core-2.1-7
  libevent-pthreads-2.1-7 libfcgi-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  liblwp-mediatypes-perl libmecab2 libtimedate-perl liburi-perl mecab-ipadic
  mecab-ipadic-utf8 mecab-utils mysql-client-8.0 mysql-client-core-8.0
  mysql-common mysql-server-8.0 mysql-server-core-8.0
Suggested packages:
  libdata-dump-perl libipc-sharedcache-perl libwww-perl mailx tinyca
The following NEW packages will be installed:
  libcgi-fast-perl libcgi-pm-perl libencode-locale-perl libevent-core-2.1-7
  libevent-pthreads-2.1-7 libfcgi-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-template-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  liblwp-mediatypes-perl libmecab2 libtimedate-perl liburi-perl mecab-ipadic
  mecab-ipadic-utf8 mecab-utils mysql-client-8.0 mysql-client-core-8.0
  mysql-common mysql-server mysql-server-8.0 mysql-server-core-8.0
0 upgraded, 25 newly installed, 0 to remove and 91 not upgraded.
Need to get 33.8 MB of archives.
After this operation, 277 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/main armhf mysql-common all 5.8+1.0.5ubuntu2 [7,496 B]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf mysql-client-core-8.0 armhf 8.0.27-0ubuntu0.20.04.1 [4,761 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf mysql-client-8.0 armhf 8.0.27-0ubuntu0.20.04.1 [22.0 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libevent-core-2.1-7 armhf 2.1.11-stable-1 [77.7 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libevent-pthreads-2.1-7 armhf 2.1.11-stable-1 [6,904 B]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libmecab2 armhf 0.996-10build1 [205 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf mysql-server-core-8.0 armhf 8.0.27-0ubuntu0.20.04.1 [20.1 MB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf mysql-server-8.0 armhf 8.0.27-0ubuntu0.20.04.1 [1,213 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libhtml-tagset-perl all 3.20-4 [12.5 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/main armhf liburi-perl all 1.76-2 [77.5 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libhtml-parser-perl armhf 3.72-5 [83.1 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libcgi-pm-perl all 4.46-1 [186 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libfcgi-perl armhf 0.79-1 [29.1 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libcgi-fast-perl all 1:2.15-1 [10.5 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libencode-locale-perl all 1.05-1 [12.3 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libhtml-template-perl all 2.97-1 [59.0 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libtimedate-perl all 2.3200-1 [34.0 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libhttp-date-perl all 6.05-1 [9,920 B]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libio-html-perl all 1.001-1 [14.9 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal/main armhf liblwp-mediatypes-perl all 6.04-1 [19.5 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libhttp-message-perl all 6.22-1 [76.1 kB]
Get:22 http://ports.ubuntu.com/ubuntu-ports focal/main armhf mecab-utils armhf 0.996-10build1 [4,792 B]
Get:23 http://ports.ubuntu.com/ubuntu-ports focal/main armhf mecab-ipadic all 2.7.0-20070801+main-2.1 [6,714 kB]
Get:24 http://ports.ubuntu.com/ubuntu-ports focal/main armhf mecab-ipadic-utf8 all 2.7.0-20070801+main-2.1 [4,380 B]
Get:25 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf mysql-server all 8.0.27-0ubuntu0.20.04.1 [9,548 B]
Fetched 33.8 MB in 7s (4,893 kB/s)                                             
Preconfiguring packages ...
Selecting previously unselected package mysql-common.
(Reading database ... 68061 files and directories currently installed.)
Preparing to unpack .../0-mysql-common_5.8+1.0.5ubuntu2_all.deb ...
Unpacking mysql-common (5.8+1.0.5ubuntu2) ...
Selecting previously unselected package mysql-client-core-8.0.
Preparing to unpack .../1-mysql-client-core-8.0_8.0.27-0ubuntu0.20.04.1_armhf.deb ...
Unpacking mysql-client-core-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Selecting previously unselected package mysql-client-8.0.
Preparing to unpack .../2-mysql-client-8.0_8.0.27-0ubuntu0.20.04.1_armhf.deb ...
Unpacking mysql-client-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Selecting previously unselected package libevent-core-2.1-7:armhf.
Preparing to unpack .../3-libevent-core-2.1-7_2.1.11-stable-1_armhf.deb ...
Unpacking libevent-core-2.1-7:armhf (2.1.11-stable-1) ...
Selecting previously unselected package libevent-pthreads-2.1-7:armhf.
Preparing to unpack .../4-libevent-pthreads-2.1-7_2.1.11-stable-1_armhf.deb ...
Unpacking libevent-pthreads-2.1-7:armhf (2.1.11-stable-1) ...
Selecting previously unselected package libmecab2:armhf.
Preparing to unpack .../5-libmecab2_0.996-10build1_armhf.deb ...
Unpacking libmecab2:armhf (0.996-10build1) ...
Selecting previously unselected package mysql-server-core-8.0.
Preparing to unpack .../6-mysql-server-core-8.0_8.0.27-0ubuntu0.20.04.1_armhf.deb ...
Unpacking mysql-server-core-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Setting up mysql-common (5.8+1.0.5ubuntu2) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Selecting previously unselected package mysql-server-8.0.
(Reading database ... 68283 files and directories currently installed.)
Preparing to unpack .../00-mysql-server-8.0_8.0.27-0ubuntu0.20.04.1_armhf.deb ...
Unpacking mysql-server-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Selecting previously unselected package libhtml-tagset-perl.
Preparing to unpack .../01-libhtml-tagset-perl_3.20-4_all.deb ...
Unpacking libhtml-tagset-perl (3.20-4) ...
Selecting previously unselected package liburi-perl.
Preparing to unpack .../02-liburi-perl_1.76-2_all.deb ...
Unpacking liburi-perl (1.76-2) ...
Selecting previously unselected package libhtml-parser-perl.
Preparing to unpack .../03-libhtml-parser-perl_3.72-5_armhf.deb ...
Unpacking libhtml-parser-perl (3.72-5) ...
Selecting previously unselected package libcgi-pm-perl.
Preparing to unpack .../04-libcgi-pm-perl_4.46-1_all.deb ...
Unpacking libcgi-pm-perl (4.46-1) ...
Selecting previously unselected package libfcgi-perl.
Preparing to unpack .../05-libfcgi-perl_0.79-1_armhf.deb ...
Unpacking libfcgi-perl (0.79-1) ...
Selecting previously unselected package libcgi-fast-perl.
Preparing to unpack .../06-libcgi-fast-perl_1%3a2.15-1_all.deb ...
Unpacking libcgi-fast-perl (1:2.15-1) ...
Selecting previously unselected package libencode-locale-perl.
Preparing to unpack .../07-libencode-locale-perl_1.05-1_all.deb ...
Unpacking libencode-locale-perl (1.05-1) ...
Selecting previously unselected package libhtml-template-perl.
Preparing to unpack .../08-libhtml-template-perl_2.97-1_all.deb ...
Unpacking libhtml-template-perl (2.97-1) ...
Selecting previously unselected package libtimedate-perl.
Preparing to unpack .../09-libtimedate-perl_2.3200-1_all.deb ...
Unpacking libtimedate-perl (2.3200-1) ...
Selecting previously unselected package libhttp-date-perl.
Preparing to unpack .../10-libhttp-date-perl_6.05-1_all.deb ...
Unpacking libhttp-date-perl (6.05-1) ...
Selecting previously unselected package libio-html-perl.
Preparing to unpack .../11-libio-html-perl_1.001-1_all.deb ...
Unpacking libio-html-perl (1.001-1) ...
Selecting previously unselected package liblwp-mediatypes-perl.
Preparing to unpack .../12-liblwp-mediatypes-perl_6.04-1_all.deb ...
Unpacking liblwp-mediatypes-perl (6.04-1) ...
Selecting previously unselected package libhttp-message-perl.
Preparing to unpack .../13-libhttp-message-perl_6.22-1_all.deb ...
Unpacking libhttp-message-perl (6.22-1) ...
Selecting previously unselected package mecab-utils.
Preparing to unpack .../14-mecab-utils_0.996-10build1_armhf.deb ...
Unpacking mecab-utils (0.996-10build1) ...
Selecting previously unselected package mecab-ipadic.
Preparing to unpack .../15-mecab-ipadic_2.7.0-20070801+main-2.1_all.deb ...
Unpacking mecab-ipadic (2.7.0-20070801+main-2.1) ...
Selecting previously unselected package mecab-ipadic-utf8.
Preparing to unpack .../16-mecab-ipadic-utf8_2.7.0-20070801+main-2.1_all.deb ...
Unpacking mecab-ipadic-utf8 (2.7.0-20070801+main-2.1) ...
Selecting previously unselected package mysql-server.
Preparing to unpack .../17-mysql-server_8.0.27-0ubuntu0.20.04.1_all.deb ...
Unpacking mysql-server (8.0.27-0ubuntu0.20.04.1) ...
Setting up libmecab2:armhf (0.996-10build1) ...
Setting up mysql-client-core-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Setting up libhtml-tagset-perl (3.20-4) ...
Setting up liblwp-mediatypes-perl (6.04-1) ...
Setting up libencode-locale-perl (1.05-1) ...
Setting up mecab-utils (0.996-10build1) ...
Setting up libevent-core-2.1-7:armhf (2.1.11-stable-1) ...
Setting up libio-html-perl (1.001-1) ...
Setting up libtimedate-perl (2.3200-1) ...
Setting up mysql-client-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Setting up libfcgi-perl (0.79-1) ...
Setting up liburi-perl (1.76-2) ...
Setting up libevent-pthreads-2.1-7:armhf (2.1.11-stable-1) ...
Setting up libhttp-date-perl (6.05-1) ...
Setting up mecab-ipadic (2.7.0-20070801+main-2.1) ...
Compiling IPA dictionary for Mecab.  This takes long time...
reading /usr/share/mecab/dic/ipadic/unk.def ... 40
emitting double-array: 100% |###########################################| 
/usr/share/mecab/dic/ipadic/model.def is not found. skipped.
reading /usr/share/mecab/dic/ipadic/Symbol.csv ... 208
reading /usr/share/mecab/dic/ipadic/Adnominal.csv ... 135
reading /usr/share/mecab/dic/ipadic/Postp-col.csv ... 91
reading /usr/share/mecab/dic/ipadic/Interjection.csv ... 252
reading /usr/share/mecab/dic/ipadic/Prefix.csv ... 221
reading /usr/share/mecab/dic/ipadic/Noun.others.csv ... 151
reading /usr/share/mecab/dic/ipadic/Adverb.csv ... 3032
reading /usr/share/mecab/dic/ipadic/Conjunction.csv ... 171
reading /usr/share/mecab/dic/ipadic/Noun.proper.csv ... 27328
reading /usr/share/mecab/dic/ipadic/Filler.csv ... 19
reading /usr/share/mecab/dic/ipadic/Noun.name.csv ... 34202
reading /usr/share/mecab/dic/ipadic/Noun.adverbal.csv ... 795
reading /usr/share/mecab/dic/ipadic/Noun.number.csv ... 42
reading /usr/share/mecab/dic/ipadic/Postp.csv ... 146
reading /usr/share/mecab/dic/ipadic/Noun.verbal.csv ... 12146
reading /usr/share/mecab/dic/ipadic/Noun.adjv.csv ... 3328
reading /usr/share/mecab/dic/ipadic/Verb.csv ... 130750
reading /usr/share/mecab/dic/ipadic/Auxil.csv ... 199
reading /usr/share/mecab/dic/ipadic/Noun.demonst.csv ... 120
reading /usr/share/mecab/dic/ipadic/Noun.org.csv ... 16668
reading /usr/share/mecab/dic/ipadic/Adj.csv ... 27210
reading /usr/share/mecab/dic/ipadic/Noun.csv ... 60477
reading /usr/share/mecab/dic/ipadic/Noun.nai.csv ... 42
reading /usr/share/mecab/dic/ipadic/Suffix.csv ... 1393
reading /usr/share/mecab/dic/ipadic/Noun.place.csv ... 72999
reading /usr/share/mecab/dic/ipadic/Others.csv ... 2
emitting double-array: 100% |###########################################| 
reading /usr/share/mecab/dic/ipadic/matrix.def ... 1316x1316
emitting matrix      : 100% |###########################################| 

done!
update-alternatives: using /var/lib/mecab/dic/ipadic to provide /var/lib/mecab/dic/debian (mecab-dictionary) in auto mode
Setting up mysql-server-core-8.0 (8.0.27-0ubuntu0.20.04.1) ...
Setting up mecab-ipadic-utf8 (2.7.0-20070801+main-2.1) ...
Compiling IPA dictionary for Mecab.  This takes long time...
reading /usr/share/mecab/dic/ipadic/unk.def ... 40
emitting double-array: 100% |###########################################| 
/usr/share/mecab/dic/ipadic/model.def is not found. skipped.
reading /usr/share/mecab/dic/ipadic/Symbol.csv ... 208
reading /usr/share/mecab/dic/ipadic/Adnominal.csv ... 135
reading /usr/share/mecab/dic/ipadic/Postp-col.csv ... 91
reading /usr/share/mecab/dic/ipadic/Interjection.csv ... 252
reading /usr/share/mecab/dic/ipadic/Prefix.csv ... 221
reading /usr/share/mecab/dic/ipadic/Noun.others.csv ... 151
reading /usr/share/mecab/dic/ipadic/Adverb.csv ... 3032
reading /usr/share/mecab/dic/ipadic/Conjunction.csv ... 171
reading /usr/share/mecab/dic/ipadic/Noun.proper.csv ... 27328
reading /usr/share/mecab/dic/ipadic/Filler.csv ... 19
reading /usr/share/mecab/dic/ipadic/Noun.name.csv ... 34202
reading /usr/share/mecab/dic/ipadic/Noun.adverbal.csv ... 795
reading /usr/share/mecab/dic/ipadic/Noun.number.csv ... 42
reading /usr/share/mecab/dic/ipadic/Postp.csv ... 146
reading /usr/share/mecab/dic/ipadic/Noun.verbal.csv ... 12146
reading /usr/share/mecab/dic/ipadic/Noun.adjv.csv ... 3328
reading /usr/share/mecab/dic/ipadic/Verb.csv ... 130750
reading /usr/share/mecab/dic/ipadic/Auxil.csv ... 199
reading /usr/share/mecab/dic/ipadic/Noun.demonst.csv ... 120
reading /usr/share/mecab/dic/ipadic/Noun.org.csv ... 16668
reading /usr/share/mecab/dic/ipadic/Adj.csv ... 27210
reading /usr/share/mecab/dic/ipadic/Noun.csv ... 60477
reading /usr/share/mecab/dic/ipadic/Noun.nai.csv ... 42
reading /usr/share/mecab/dic/ipadic/Suffix.csv ... 1393
reading /usr/share/mecab/dic/ipadic/Noun.place.csv ... 72999
reading /usr/share/mecab/dic/ipadic/Others.csv ... 2
emitting double-array: 100% |###########################################| 
reading /usr/share/mecab/dic/ipadic/matrix.def ... 1316x1316
emitting matrix      : 100% |###########################################| 

done!
update-alternatives: using /var/lib/mecab/dic/ipadic-utf8 to provide /var/lib/mecab/dic/debian (mecab-dictionary) in auto mode
Setting up libhtml-parser-perl (3.72-5) ...
Setting up libhttp-message-perl (6.22-1) ...
Setting up mysql-server-8.0 (8.0.27-0ubuntu0.20.04.1) ...
update-alternatives: using /etc/mysql/mysql.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Renaming removed key_buffer and myisam-recover options (if present)
mysqld will log errors to /var/log/mysql/error.log
mysqld is running as pid 10813
Created symlink /etc/systemd/system/multi-user.target.wants/mysql.service → /lib/systemd/system/mysql.service.
Setting up libcgi-pm-perl (4.46-1) ...
Setting up libhtml-template-perl (2.97-1) ...
Setting up mysql-server (8.0.27-0ubuntu0.20.04.1) ...
Setting up libcgi-fast-perl (1:2.15-1) ...
Processing triggers for systemd (245.4-4ubuntu3.11) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  php7.1-mysql
0 upgraded, 1 newly installed, 0 to remove and 91 not upgraded.
Need to get 98.7 kB of archives.
After this operation, 278 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main armhf php7.1-mysql armhf 7.1.33-44+ubuntu20.04.1+deb.sury.org+1 [98.7 kB]
Fetched 98.7 kB in 0s (446 kB/s)      
Selecting previously unselected package php7.1-mysql.
(Reading database ... 68653 files and directories currently installed.)
Preparing to unpack .../php7.1-mysql_7.1.33-44+ubuntu20.04.1+deb.sury.org+1_armhf.deb ...
Unpacking php7.1-mysql (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...
Setting up php7.1-mysql (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.1/mods-available/mysqlnd.ini with new version

Creating config file /etc/php/7.1/mods-available/mysqli.ini with new version

Creating config file /etc/php/7.1/mods-available/pdo_mysql.ini with new version
Processing triggers for libapache2-mod-php7.1 (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...
Processing triggers for php7.1-cli (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libsqlite0 sqlite3
Suggested packages:
  sqlite-doc sqlite3-doc
The following NEW packages will be installed:
  libsqlite0 php7.1-sqlite3 sqlite sqlite3
0 upgraded, 4 newly installed, 0 to remove and 91 not upgraded.
Need to get 903 kB of archives.
After this operation, 2,154 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main armhf php7.1-sqlite3 armhf 7.1.33-44+ubuntu20.04.1+deb.sury.org+1 [20.9 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf libsqlite0 armhf 2.8.17-15fakesync1build1 [134 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf sqlite armhf 2.8.17-15fakesync1build1 [15.3 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf sqlite3 armhf 3.31.1-4ubuntu0.2 [732 kB]
Fetched 903 kB in 0s (1,977 kB/s)
Selecting previously unselected package libsqlite0.
(Reading database ... 68666 files and directories currently installed.)
Preparing to unpack .../libsqlite0_2.8.17-15fakesync1build1_armhf.deb ...
Unpacking libsqlite0 (2.8.17-15fakesync1build1) ...
Selecting previously unselected package php7.1-sqlite3.
Preparing to unpack .../php7.1-sqlite3_7.1.33-44+ubuntu20.04.1+deb.sury.org+1_armhf.deb ...
Unpacking php7.1-sqlite3 (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...
Selecting previously unselected package sqlite.
Preparing to unpack .../sqlite_2.8.17-15fakesync1build1_armhf.deb ...
Unpacking sqlite (2.8.17-15fakesync1build1) ...
Selecting previously unselected package sqlite3.
Preparing to unpack .../sqlite3_3.31.1-4ubuntu0.2_armhf.deb ...
Unpacking sqlite3 (3.31.1-4ubuntu0.2) ...
Setting up libsqlite0 (2.8.17-15fakesync1build1) ...
Setting up sqlite (2.8.17-15fakesync1build1) ...
Setting up php7.1-sqlite3 (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...

Creating config file /etc/php/7.1/mods-available/sqlite3.ini with new version

Creating config file /etc/php/7.1/mods-available/pdo_sqlite.ini with new version
Setting up sqlite3 (3.31.1-4ubuntu0.2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libapache2-mod-php7.1 (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...
Processing triggers for php7.1-cli (7.1.33-44+ubuntu20.04.1+deb.sury.org+1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Now we're going to set up our first Admin Portal user.
Please enter the username you wish to use: quiqqy
Please enter a password: *********
We will now set the rank for quiqqy
At the moment, this does nothing. However in later releases, we plan to restrict who can do what.
1: First Rank
2: Second Rank
3: Third Rank
Please enter a rank number [1-3]: 1
That's all the informatio I'll need for now.
Setting up the cowfc users database
mysql: [Warning] Using a password on the command line interface can be insecure.
Now importing dumped cowfc database...
mysql: [Warning] Using a password on the command line interface can be insecure.
Now inserting user quiqqy into the database with password ******, hashed as $2y$10$qKefVhxKl8zGZcOum61c5O3OsV9HkwEq5P4i3EMMvL5e.nN3h.geu.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rank) values ('quiqqy','$2y$10$qKefVhxKl8zGZcOum61c5O3OsV9HkwEq5P4i3EMMvL5e.nN3h' at line 1
For added security, we recommend setting up Google's reCaptcha.

However, not many people would care about this, so we're making it optional.

Feel free to press the ENTER key at the prompt, to skip reCaptcha setup, or 'y' to proceed with recaptcha setup.
Would you like to set up reCaptcha on this server? [y/N]: n
Checking if there is a cron available for root
no crontab for root
No cron job is currently installed
Working the magic. Hang tight!
/usr/bin/crontab
Creating the cron job now!
Done!
This recent CoWFC update allows you to set your server's name
This is useful if you want to whitelabel your server, and not advertise it as CoWFC
Please enter the server name, or press ENTER to accept the default [CoWFC]: WFCReborn
Setting server name to WFCReborn
Moving the configuration file for more security...
Done!
Finishing...
Thank you for installing CoWFC.
If you wish to access the admin GUI, please go to http://94.14.142.213/?page=admin&section=Dashboard
Please hit the ENTER key to reboot now, or press ctrl+c and reboot whenever it is convenient for you: [ENTER] 
Connection to 192.168.0.31 closed by remote host.
Connection to 192.168.0.31 closed.
quimo@Evans-Air ~ % ssh ubuntu@192.168.0.31
ubuntu@192.168.0.31's password: 
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1042-raspi armv7l)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Jan  5 14:55:45 UTC 2022

  System load:            3.72
  Usage of /:             73.7% of 3.27GB
  Memory usage:           13%
  Swap usage:             0%
  Temperature:            56.0 C
  Processes:              150
  Users logged in:        0
  IPv4 address for wlan0: 192.168.0.31
  IPv6 address for wlan0: fda6:4e48:4dd5:0:dea6:32ff:fe86:2fd9


91 updates can be applied immediately.
45 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable


Last login: Wed Jan  5 14:33:56 2022 from 192.168.0.10
ubuntu@ubuntu:~$ sudo su
root@ubuntu:/home/ubuntu# 

P.s. I removed my password with *** as its my normal password...

**Comment by quimodotcom** [comment]
P.p.s This was ran on a Ubuntu Server 20.04.03 LTS armhf Raspberry Pi 4 4GB Ram Edition

**Comment by EnergyCube** [comment]
Yeah something is wrong :
**ERROR 1064 (42000) at line 1**: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rank) values ('quiqqy','$2y$10$qKefVhxKl8zGZcOum61c5O3OsV9HkwEq5P4i3EMMvL5e.nN3h' at line 1

Look like the script can't add the user to the list of user in the db.
That's strange... If Raspberry is compatible with Ubuntu 16 or 18 you could use the cowfc_for_aws_ubuntu_16.sh
But it should work since you used the cowfc.sh script that support Ubuntu 20.

I don't have enough time to fix that error and can only recommend you to try to add the value yourself in the db and try to connect again. If anyone can found how to fix that I will gladly accept pull requests.

**Comment by quimodotcom** [comment]
> Yeah something is wrong : **ERROR 1064 (42000) at line 1**: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rank) values ('quiqqy','$2y$10$qKefVhxKl8zGZcOum61c5O3OsV9HkwEq5P4i3EMMvL5e.nN3h' at line 1
> 
> Look like the script can't add the user to the list of user in the db. That's strange... If Raspberry is compatible with Ubuntu 16 or 18 you could use the cowfc_for_aws_ubuntu_16.sh But it should work since you used the cowfc.sh script that support Ubuntu 20.
> 
> I don't have enough time to fix that error and can only recommend you to try to add the value yourself in the db and try to connect again. If anyone can found how to fix that I will gladly accept pull requests.

Thx for the reply, Ima try add the user to the db. Shouldn't be too hard, right?

**Comment by quimodotcom** [comment]
actually have no idea how to add the user to the db file. if you could walk me through it or show me an example file that would be great!
